services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/load-balanced-reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-config/ssl:/etc/ssl:ro
      - ./nginx-config/html:/var/www/html:ro
    restart: unless-stopped
